title: "Ali Demir"
name: "Ali Demir"
description: "PhD Researcher in Empirical Economics"

url: "https://alidemir1995ad-alt.github.io"
baseurl: "/alidemir"
timezone: Europe/Berlin

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-gist
  - jekyll-paginate
